services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env-non-dev
    depends_on:
      - db
      - redis
    networks:
      - app-network

  celery:
    build:
      context: .
      dockerfile: backend.Dockerfile
    command: celery -A app.tasks.celery_app worker --loglevel=info
    volumes:
      - ./uploads:/app/uploads
    env_file:
      - .env-non-dev
    depends_on:
      - backend
      - redis
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "8181:80"
    environment:
      - VITE_API_URL=http://api.rondo.svnoready.ru
    depends_on:
      - backend
    networks:
      - app-network

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=rondo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

volumes:
  postgres_data:
  redis_data:


networks:
  app-network:
    driver: bridge
