"""migr2

Revision ID: 0278f9dd554c
Revises: 364df179357d
Create Date: 2025-03-08 23:57:42.959528

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0278f9dd554c'
down_revision: str | None = '364df179357d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
