"""update model for tags v8

Revision ID: 031b8e3016ed
Revises: d41c1b921f62
Create Date: 2025-03-23 12:44:46.947940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '031b8e3016ed'
down_revision: Union[str, None] = 'd41c1b921f62'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tag_id'), 'tag', ['id'], unique=False)
    op.create_index(op.f('ix_tag_name'), 'tag', ['name'], unique=False)
    op.create_table('event_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_tags_event_id'), 'event_tags', ['event_id'], unique=False)
    op.create_index(op.f('ix_event_tags_id'), 'event_tags', ['id'], unique=False)
    op.create_index(op.f('ix_event_tags_tag_id'), 'event_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_tags_tag_id'), table_name='event_tags')
    op.drop_index(op.f('ix_event_tags_id'), table_name='event_tags')
    op.drop_index(op.f('ix_event_tags_event_id'), table_name='event_tags')
    op.drop_table('event_tags')
    op.drop_index(op.f('ix_tag_name'), table_name='tag')
    op.drop_index(op.f('ix_tag_id'), table_name='tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
