"""Fix

Revision ID: 04fd07638007
Revises: 3bcf7fe2413e
Create Date: 2025-03-09 14:59:09.788826

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '04fd07638007'
down_revision: str | None = '3bcf7fe2413e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
