"""add new model

Revision ID: 0e7afd9451ea
Revises: 3cdd9e920f2f
Create Date: 2025-03-11 15:06:10.175499

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '0e7afd9451ea'
down_revision: str | None = '3cdd9e920f2f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
