"""add courts_reservation

Revision ID: 15d6032c2291
Revises: 486095e6c46b
Create Date: 2025-04-12 13:10:57.650741

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '15d6032c2291'
down_revision: Union[str, None] = '486095e6c46b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_reservations', sa.Column('is_temporary', sa.Boolean(), nullable=True))
    op.add_column('court_reservations', sa.Column('expires_at', sa.DateTime(), nullable=True))
    op.add_column('court_reservations', sa.Column('is_confirmed', sa.Boolean(), nullable=True))
    op.alter_column('court_reservations', 'court_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('court_reservations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('court_reservations', 'date',
               existing_type=sa.DATE(),
               type_=sa.String(),
               nullable=True)
    op.alter_column('court_reservations', 'time',
               existing_type=postgresql.TIME(),
               type_=sa.String(),
               nullable=True)
    op.create_index(op.f('ix_court_reservations_id'), 'court_reservations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_court_reservations_id'), table_name='court_reservations')
    op.alter_column('court_reservations', 'time',
               existing_type=sa.String(),
               type_=postgresql.TIME(),
               nullable=False)
    op.alter_column('court_reservations', 'date',
               existing_type=sa.String(),
               type_=sa.DATE(),
               nullable=False)
    op.alter_column('court_reservations', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('court_reservations', 'court_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('court_reservations', 'is_confirmed')
    op.drop_column('court_reservations', 'expires_at')
    op.drop_column('court_reservations', 'is_temporary')
    # ### end Alembic commands ###
