"""migr3

Revision ID: 35e14a5bc95d
Revises: 0278f9dd554c
Create Date: 2025-03-09 00:08:39.068380

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '35e14a5bc95d'
down_revision: str | None = '0278f9dd554c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
