"""add courts

Revision ID: 42552a1741db
Revises: ba12d0fc9f75
Create Date: 2025-04-13 17:17:29.773301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42552a1741db'
down_revision: Union[str, None] = 'ba12d0fc9f75'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('court_reservations', 'is_temporary')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_reservations', sa.Column('is_temporary', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
