"""Add count_members column

Revision ID: 5a504192cc32
Revises: 4f8ed6af6360
Create Date: 2025-03-20 13:39:55.409139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a504192cc32'
down_revision: Union[str, None] = '4f8ed6af6360'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Сначала добавляем колонку как nullable
    op.add_column('event', sa.Column('count_members', sa.Integer(), nullable=True))
    
    # Устанавливаем значение по умолчанию для существующих записей
    op.execute("UPDATE event SET count_members = 0")
    
    # Делаем колонку NOT NULL
    op.alter_column('event', 'count_members',
                    existing_type=sa.Integer(),
                    nullable=False,
                    server_default='0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'count_members')
    # ### end Alembic commands ###
