"""add courts

Revision ID: 6b5f47d56a4d
Revises: 6e1144fc0da1
Create Date: 2025-04-12 00:32:03.136197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6b5f47d56a4d'
down_revision: Union[str, None] = '6e1144fc0da1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courts', 'not_available_dates',
               existing_type=postgresql.ARRAY(postgresql.TIMESTAMP()),
               type_=sa.ARRAY(sa.Date()),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('courts', 'not_available_dates',
               existing_type=sa.ARRAY(sa.Date()),
               type_=postgresql.ARRAY(postgresql.TIMESTAMP()),
               existing_nullable=True)
    # ### end Alembic commands ###
