"""add c2

Revision ID: 7a38fff0690b
Revises: 9dee331ebebf
Create Date: 2025-04-04 15:26:29.505778

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a38fff0690b'
down_revision: Union[str, None] = '9dee331ebebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coworking_reservation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('coworking_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['coworking_id'], ['coworking.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coworking_reservation_id'), 'coworking_reservation', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coworking_reservation_id'), table_name='coworking_reservation')
    op.drop_table('coworking_reservation')
    # ### end Alembic commands ###
