"""a7

Revision ID: 90fa8ad49ece
Revises: 3e8d9b6927fe
Create Date: 2025-04-18 14:11:06.513593

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90fa8ad49ece'
down_revision: Union[str, None] = '3e8d9b6927fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_reservations', sa.Column('payment_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('court_reservations', 'payment_id')
    # ### end Alembic commands ###
