"""add coworking

Revision ID: 9dee331ebebf
Revises: c8c9530752a5
Create Date: 2025-04-03 22:39:21.337417

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dee331ebebf'
down_revision: Union[str, None] = 'c8c9530752a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coworking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_coworking_id'), 'coworking', ['id'], unique=False)
    op.create_index(op.f('ix_coworking_name'), 'coworking', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coworking_name'), table_name='coworking')
    op.drop_index(op.f('ix_coworking_id'), table_name='coworking')
    op.drop_table('coworking')
    # ### end Alembic commands ###
