"""Initial migration222

Revision ID: a3438f47f31f
Revises: 90fa8ad49ece
Create Date: 2025-05-21 21:47:11.819331

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3438f47f31f'
down_revision: Union[str, None] = '90fa8ad49ece'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('court_reservations', sa.Column('is_social', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('court_reservations', 'is_social')
    # ### end Alembic commands ###
