"""update index model

Revision ID: b8a6476f35ad
Revises: 5a504192cc32
Create Date: 2025-03-20 22:25:16.466376

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b8a6476f35ad'
down_revision: Union[str, None] = '5a504192cc32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_registration_event_id'), 'registration', ['event_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_registration_event_id'), table_name='registration')
    # ### end Alembic commands ###
