"""update model for tags v7

Revision ID: d41c1b921f62
Revises: 2fd47454f7cd
Create Date: 2025-03-22 18:39:51.928300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd41c1b921f62'
down_revision: Union[str, None] = '2fd47454f7cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('registration_event_id_fkey', 'registration', type_='foreignkey')
    op.create_foreign_key(None, 'registration', 'event', ['event_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registration', type_='foreignkey')
    op.create_foreign_key('registration_event_id_fkey', 'registration', 'event', ['event_id'], ['id'])
    # ### end Alembic commands ###
