"""add ne

Revision ID: eae47bb85d48
Revises: 2ceacdd585cb
Create Date: 2025-03-13 20:19:19.404530

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = 'eae47bb85d48'
down_revision: str | None = '2ceacdd585cb'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
